// <auto-generated />
using System;
using GoodsExchange.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodsExchange.Data.Migrations
{
    [DbContext(typeof(GoodsExchangeDbContext))]
    [Migration("20240526031931_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GoodsExchange.Data.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("94d367d0-61d1-4979-ba88-99b2f83fe9eb"),
                            CategoryName = "Stationery"
                        },
                        new
                        {
                            CategoryId = new Guid("ce74fc86-9cdf-4805-960c-e4647f21f6cf"),
                            CategoryName = "Drawing Supplies"
                        },
                        new
                        {
                            CategoryId = new Guid("f0fde948-4e6d-4412-a417-3eac5f927d44"),
                            CategoryName = "Books and Materials"
                        },
                        new
                        {
                            CategoryId = new Guid("e0b58109-b173-442a-86d5-972e0bc3e093"),
                            CategoryName = "Tech Devices"
                        });
                });

            modelBuilder.Entity("GoodsExchange.Data.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ProductImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("d844fbc5-f0eb-4444-b16c-5f042a6ea073"),
                            ApprovedDate = new DateTime(2023, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("94d367d0-61d1-4979-ba88-99b2f83fe9eb"),
                            Description = "Premium ballpoint pen for everyday use",
                            IsApproved = true,
                            Price = 2.99f,
                            ProductImageUrl = "https://example.com/ballpoint-pen.jpg",
                            ProductName = "Ballpoint Pen",
                            Status = true,
                            UploadDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = new Guid("05d96e05-4d3a-4e3a-8bea-eeec2fcb33ec"),
                            ApprovedDate = new DateTime(2023, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("94d367d0-61d1-4979-ba88-99b2f83fe9eb"),
                            Description = "Durable mechanical pencil with 0.5mm lead",
                            IsApproved = true,
                            Price = 4.5f,
                            ProductImageUrl = "https://example.com/mechanical-pencil.jpg",
                            ProductName = "Mechanical Pencil",
                            Status = true,
                            UploadDate = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = new Guid("3f87323e-7a89-43fc-b6d4-18919b4832cf"),
                            ApprovedDate = new DateTime(2023, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("ce74fc86-9cdf-4805-960c-e4647f21f6cf"),
                            Description = "Set of 24 high-quality colored pencils",
                            IsApproved = true,
                            Price = 9.99f,
                            ProductImageUrl = "https://example.com/colored-pencils.jpg",
                            ProductName = "Colored Pencils",
                            Status = true,
                            UploadDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = new Guid("c6f8e167-7df8-42ec-9473-a89998696daa"),
                            ApprovedDate = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("ce74fc86-9cdf-4805-960c-e4647f21f6cf"),
                            Description = "A5 size sketchbook with acid-free pages",
                            IsApproved = true,
                            Price = 12.99f,
                            ProductImageUrl = "https://example.com/sketchbook.jpg",
                            ProductName = "Sketchbook",
                            Status = true,
                            UploadDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = new Guid("91047c2e-274e-4695-a7df-1642d3fa017c"),
                            ApprovedDate = new DateTime(2023, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("f0fde948-4e6d-4412-a417-3eac5f927d44"),
                            Description = "High school-level chemistry textbook",
                            IsApproved = true,
                            Price = 29.99f,
                            ProductImageUrl = "https://example.com/chemistry-textbook.jpg",
                            ProductName = "Chemistry Textbook",
                            Status = true,
                            UploadDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = new Guid("b441c407-5ccb-4e18-b8b8-74acb20c6eae"),
                            ApprovedDate = new DateTime(2023, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("f0fde948-4e6d-4412-a417-3eac5f927d44"),
                            Description = "Grade 7 mathematics practice workbook",
                            IsApproved = true,
                            Price = 14.99f,
                            ProductImageUrl = "https://example.com/math-workbook.jpg",
                            ProductName = "Mathematics Workbook",
                            Status = true,
                            UploadDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = new Guid("ed187a9a-5a8a-4c91-83e6-aa21b8a6759f"),
                            ApprovedDate = new DateTime(2023, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("e0b58109-b173-442a-86d5-972e0bc3e093"),
                            Description = "Scientific calculator with graphing capabilities",
                            IsApproved = true,
                            Price = 59.99f,
                            ProductImageUrl = "https://example.com/graphing-calculator.jpg",
                            ProductName = "Graphing Calculator",
                            Status = true,
                            UploadDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = new Guid("0e0f7879-04dd-45ba-8bda-1e80216f6030"),
                            ApprovedDate = new DateTime(2023, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("e0b58109-b173-442a-86d5-972e0bc3e093"),
                            Description = "High-performance tablet for educational use",
                            IsApproved = true,
                            Price = 299.99f,
                            ProductImageUrl = "https://example.com/tablet-computer.jpg",
                            ProductName = "Tablet Computer",
                            Status = true,
                            UploadDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = new Guid("02b2f7e7-6d9b-413e-b2f1-2d045be2a2df"),
                            ApprovedDate = new DateTime(2023, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("94d367d0-61d1-4979-ba88-99b2f83fe9eb"),
                            Description = "Durable 30cm plastic ruler",
                            IsApproved = true,
                            Price = 1.5f,
                            ProductImageUrl = "https://example.com/ruler.jpg",
                            ProductName = "Ruler",
                            Status = true,
                            UploadDate = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = new Guid("7a52b01c-203c-4ce8-bd1b-9a65dc49af56"),
                            ApprovedDate = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("94d367d0-61d1-4979-ba88-99b2f83fe9eb"),
                            Description = "Set of 4 fluorescent highlighters",
                            IsApproved = true,
                            Price = 3.99f,
                            ProductImageUrl = "https://example.com/highlighter-set.jpg",
                            ProductName = "Highlighter Set",
                            Status = true,
                            UploadDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GoodsExchange.Data.Models.Rate", b =>
                {
                    b.Property<Guid>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NumberStars")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RatingUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RatingId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("RatingUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Ratings", (string)null);
                });

            modelBuilder.Entity("GoodsExchange.Data.Models.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ReportingUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReportId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReportingUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("GoodsExchange.Data.Models.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("e398cee3-6381-4a52-aaf5-20a2e9b54810"),
                            RoleName = "Administrator"
                        },
                        new
                        {
                            RoleId = new Guid("3d446530-061e-4a88-ae6c-1b6a6190a693"),
                            RoleName = "Moderator"
                        },
                        new
                        {
                            RoleId = new Guid("ca5af2d0-6b92-49bb-91ff-2e5d9f1279d4"),
                            RoleName = "Buyer"
                        },
                        new
                        {
                            RoleId = new Guid("d81f428f-9572-47f1-a980-69de7a1e348b"),
                            RoleName = "Seller"
                        });
                });

            modelBuilder.Entity("GoodsExchange.Data.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UserImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("0af02748-9d43-4110-81e5-93d9ece8cfda"),
                            DateOfBirth = new DateTime(1985, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "password123",
                            PhoneNumber = "555-1234567",
                            Status = true,
                            UserImageUrl = "",
                            UserName = "johndoe"
                        },
                        new
                        {
                            UserId = new Guid("b6b6e80f-cc04-43e3-800f-a3c89b3ba017"),
                            DateOfBirth = new DateTime(1992, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Password = "password456",
                            PhoneNumber = "555-7654321",
                            Status = true,
                            UserImageUrl = "",
                            UserName = "janesmith"
                        },
                        new
                        {
                            UserId = new Guid("99d274e6-fa23-4d1c-8f8a-097b3886caad"),
                            DateOfBirth = new DateTime(1978, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.johnson@example.com",
                            FirstName = "Michael",
                            LastName = "Johnson",
                            Password = "password789",
                            PhoneNumber = "555-2468013",
                            Status = false,
                            UserImageUrl = "",
                            UserName = "michaeljohnson"
                        },
                        new
                        {
                            UserId = new Guid("50248ca1-b632-4e16-b1a4-9aadd8e08e7c"),
                            DateOfBirth = new DateTime(1990, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.davis@example.com",
                            FirstName = "Emily",
                            LastName = "Davis",
                            Password = "passwordabc",
                            PhoneNumber = "555-3691258",
                            Status = true,
                            UserImageUrl = "",
                            UserName = "emilydavis"
                        },
                        new
                        {
                            UserId = new Guid("d6446689-2743-460b-82c3-d25b21f87b13"),
                            DateOfBirth = new DateTime(1982, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.lee@example.com",
                            FirstName = "David",
                            LastName = "Lee",
                            Password = "passworddef",
                            PhoneNumber = "555-4725836",
                            Status = false,
                            UserImageUrl = "",
                            UserName = "davidlee"
                        });
                });

            modelBuilder.Entity("GoodsExchange.Data.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("0af02748-9d43-4110-81e5-93d9ece8cfda"),
                            RoleId = new Guid("e398cee3-6381-4a52-aaf5-20a2e9b54810")
                        },
                        new
                        {
                            UserId = new Guid("b6b6e80f-cc04-43e3-800f-a3c89b3ba017"),
                            RoleId = new Guid("3d446530-061e-4a88-ae6c-1b6a6190a693")
                        },
                        new
                        {
                            UserId = new Guid("99d274e6-fa23-4d1c-8f8a-097b3886caad"),
                            RoleId = new Guid("ca5af2d0-6b92-49bb-91ff-2e5d9f1279d4")
                        },
                        new
                        {
                            UserId = new Guid("50248ca1-b632-4e16-b1a4-9aadd8e08e7c"),
                            RoleId = new Guid("ca5af2d0-6b92-49bb-91ff-2e5d9f1279d4")
                        },
                        new
                        {
                            UserId = new Guid("d6446689-2743-460b-82c3-d25b21f87b13"),
                            RoleId = new Guid("d81f428f-9572-47f1-a980-69de7a1e348b")
                        });
                });

            modelBuilder.Entity("GoodsExchange.Data.Models.Product", b =>
                {
                    b.HasOne("GoodsExchange.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GoodsExchange.Data.Models.Rate", b =>
                {
                    b.HasOne("GoodsExchange.Data.Models.Product", "Product")
                        .WithOne("Rate")
                        .HasForeignKey("GoodsExchange.Data.Models.Rate", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoodsExchange.Data.Models.User", "RatingGiven")
                        .WithMany("RatingsGiven")
                        .HasForeignKey("RatingUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GoodsExchange.Data.Models.User", "RatingReceived")
                        .WithMany("RatingsReceived")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RatingGiven");

                    b.Navigation("RatingReceived");
                });

            modelBuilder.Entity("GoodsExchange.Data.Models.Report", b =>
                {
                    b.HasOne("GoodsExchange.Data.Models.Product", "Product")
                        .WithMany("Report")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GoodsExchange.Data.Models.User", "ReportMade")
                        .WithMany("ReportsMade")
                        .HasForeignKey("ReportingUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GoodsExchange.Data.Models.User", "ReportReceived")
                        .WithMany("ReportsReceived")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ReportMade");

                    b.Navigation("ReportReceived");
                });

            modelBuilder.Entity("GoodsExchange.Data.Models.UserRole", b =>
                {
                    b.HasOne("GoodsExchange.Data.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoodsExchange.Data.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoodsExchange.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GoodsExchange.Data.Models.Product", b =>
                {
                    b.Navigation("Rate")
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("GoodsExchange.Data.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GoodsExchange.Data.Models.User", b =>
                {
                    b.Navigation("RatingsGiven");

                    b.Navigation("RatingsReceived");

                    b.Navigation("ReportsMade");

                    b.Navigation("ReportsReceived");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
